# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    prefer_const_constructors : false
    unnecessary_string_interpolations : false
    always_declare_return_types : false
    always_require_non_null_named_parameters : false
    annotate_overrides : false
    avoid_init_to_null : false
    avoid_null_checks_in_equality_operators : false
    avoid_relative_lib_imports : false
    avoid_return_types_on_setters : false
    avoid_shadowing_type_parameters : false
    avoid_single_cascade_in_expression_statements : false
    avoid_types_as_parameter_names : false
    await_only_futures : false
    camel_case_extensions : false
    curly_braces_in_flow_control_structures : false
    empty_catches : false
    empty_constructor_bodies : false
    library_names : false
    library_prefixes : false
    no_duplicate_case_values : false
    null_closures : false
    omit_local_variable_types : false
    prefer_adjacent_string_concatenation : false
    prefer_collection_literals : false
    prefer_conditional_assignment : false
    prefer_contains : false
    prefer_equal_for_default_values : false
    prefer_final_fields : false
    prefer_for_elements_to_map_fromIterable : false
    prefer_generic_function_type_aliases : false
    prefer_if_null_operators : false
    prefer_inlined_adds : false
    prefer_is_empty : false
    prefer_is_not_empty : false
    prefer_iterable_whereType : false
    prefer_single_quotes : false
    prefer_spread_collections : false
    recursive_getters : false
    slash_for_doc_comments : false
    sort_child_properties_last : false
    type_init_formals : false
    unawaited_futures : false
    unnecessary_brace_in_string_interps : false
    unnecessary_const : false
    unnecessary_getters_setters : false
    unnecessary_new : false
    unnecessary_null_in_if_null_operators : false
    unnecessary_this : false
    unrelated_type_equality_checks : false
    unsafe_html : false
    use_full_hex_values_for_flutter_colors : false
    use_function_type_syntax_for_parameters : false
    use_rethrow_when_possible : false
    valid_regexps : false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
